apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Dynamo DB Storage
  description: DynamoDB storage plugin for Reekoh IoT Platform.
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - dynamo
    - dynamoDB
  config:
    accessKeyId:
      label: Access Key ID
      type: String
      maxLength: 1000
      required: true
      help: "AWS Access Key ID."
    secretAccessKey:
      label: Secret Access Key
      type: Password
      maxLength: 1000
      required: true
      help: "Matching Secret Access key for AWS Access Key ID."
    region:
      label: Region
      type: String
      maxLength: 1000
      required: true
      help: "Region where the Dynamo DB Table is location i.e. (us-west-2)."
    table:
      label: Table
      type: String
      maxLength: 1000
      required: true
      help: "DynamoDB Table."

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??